language: ruby
addons:
  ssh_known_hosts: FTP_DEPLOY_HOST
before_script:
- npm install
- rm -rf public
- bundle exec jekyll build
- openssl aes-256-cbc -K $encrypted_c584d00743f5_key -iv $encrypted_c584d00743f5_iv
  -in oregon_key.ppk.enc -out /tmp/oregon_key.ppk -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/oregon_key.ppk
- ssh-add /tmp/oregon_key.ppk
script:
- npm run deploy
branches:
  only:
  - main


